In [19]:
import numpy as np

In [20]:
### create an array

In [21]:
a1 = np.array([1,2,3,4,5])   ## 1d array
a2 = np.array([[1,2,3,4,5]])   ## 2d array
a3 = np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])   ## 2d array
a4 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])  ## 3d array
a5 = np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]],
               [[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]])  ## 3d array

In [22]:
print(len(a1))
print(len(a2))
print(len(a3))
print(len(a4))
print(len(a5))

5
1
3
1
2


In [23]:
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)
print(a4.ndim)
print(a5.ndim)

1
2
2
3
3


In [24]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)

int64
int64
int64
int64
int64


In [25]:
a6 = np.array([1,2,4.5,4,22,44.3])
a6

array([ 1. ,  2. ,  4.5,  4. , 22. , 44.3])

In [26]:
a6.dtype

dtype('float64')

In [27]:
a7 = np.array([1,2,4.5,4,22,"Umang"])
a7

array(['1', '2', '4.5', '4', '22', 'Umang'], dtype='<U32')

In [28]:
a7.dtype

dtype('<U32')

In [29]:
print(len(a1))
print(len(a2))
print(len(a3))
print(len(a4))
print(len(a5))

5
1
3
1
2


In [30]:
print(a1.shape)
print(a2.shape)
print(a3.shape)
print(a4.shape)
print(a5.shape)

(5,)
(1, 5)
(3, 5)
(1, 3, 5)
(2, 3, 5)


In [31]:
### random numbers

In [32]:
r1 = np.random.randint(100)   ## one random number b/w 0 to 99
r1

79

In [33]:
np.random.seed(10)
r1 = np.random.randint(100)   ## one random number b/w 0 to 99
r1

9

In [34]:
np.random.seed(100)
r1 = np.random.randint(100)   ## one random number b/w 0 to 99
r1

8

In [35]:
r1 = np.random.randint(100,500)   ## one random number b/w 100 to 499
r1

380

In [36]:
r1 = np.random.randint(100,500,10)   ## 10 random number b/w 100 to 499
r1

array([423, 459, 443, 179, 494, 450, 454, 153, 166, 326])

In [37]:
r1 = np.random.randint(100,500,(10,8))   ## 10x8 random array b/w 100 to 499
r1

array([[114, 390, 340, 380, 243, 328, 463, 416],
       [158, 237, 193, 186, 486, 255, 464, 488],
       [485, 241, 345, 311, 200, 104, 191, 423],
       [235, 149, 293, 417, 370, 283, 351, 436],
       [102, 477, 205, 163, 281, 383, 412, 338],
       [469, 403, 267, 465, 394, 272, 374, 292],
       [302, 373, 172, 113, 206, 130, 117, 153],
       [168, 447, 281, 434, 100, 113, 285, 462],
       [231, 170, 231, 312, 307, 494, 315, 231],
       [461, 276, 280, 399, 136, 361, 427, 138]])

In [38]:
r1 = np.random.randint(100,500,(10,8,2))   ## 10x8x2 random array b/w 100 to 499
r1

array([[[314, 194],
        [326, 270],
        [440, 195],
        [214, 337],
        [219, 176],
        [389, 414],
        [202, 356],
        [350, 283]],

       [[326, 409],
        [296, 406],
        [353, 109],
        [377, 362],
        [265, 458],
        [222, 216],
        [286, 395],
        [207, 322]],

       [[407, 386],
        [477, 166],
        [343, 373],
        [401, 189],
        [391, 116],
        [112, 442],
        [209, 167],
        [320, 323]],

       [[376, 238],
        [364, 300],
        [496, 246],
        [449, 475],
        [192, 144],
        [345, 157],
        [483, 356],
        [173, 332]],

       [[282, 422],
        [244, 489],
        [446, 134],
        [450, 282],
        [177, 312],
        [485, 114],
        [471, 389],
        [248, 268]],

       [[124, 384],
        [310, 235],
        [102, 163],
        [469, 230],
        [315, 245],
        [337, 318],
        [350, 324],
        [174, 386]],

       [[167, 256],
        

In [39]:
r1 = np.random.uniform(100,500,10)   ## 10 random number b/w 100 to 499
r1

array([479.41968113, 208.08988431, 488.9616572 , 370.92698626,
       423.91983969, 277.22769575, 143.69641158, 488.15696571,
       255.39193491, 278.61559825])

In [40]:
r1 = np.random.uniform(100,500,10)   ## 10 random number b/w 100 to 499
r1 = np.round(r1,2)
r1

array([176.46, 456.46, 289.69, 184.95, 343.66, 307.08, 261.18, 229.21,
       335.43, 255.51])

In [41]:
## array indexing and slicing

In [42]:
np.random.seed(100)
r1 = np.random.randint(100,500,(10,8))
r1

array([[108, 380, 423, 459, 443, 179, 494, 450],
       [454, 153, 166, 326, 114, 390, 340, 380],
       [243, 328, 463, 416, 158, 237, 193, 186],
       [486, 255, 464, 488, 485, 241, 345, 311],
       [200, 104, 191, 423, 235, 149, 293, 417],
       [370, 283, 351, 436, 102, 477, 205, 163],
       [281, 383, 412, 338, 469, 403, 267, 465],
       [394, 272, 374, 292, 302, 373, 172, 113],
       [206, 130, 117, 153, 168, 447, 281, 434],
       [100, 113, 285, 462, 231, 170, 231, 312]])

In [43]:
len(r1)

10

In [44]:
r1[0]

array([108, 380, 423, 459, 443, 179, 494, 450])

In [45]:
r1[3]

array([486, 255, 464, 488, 485, 241, 345, 311])

In [46]:
r1[-2]

array([206, 130, 117, 153, 168, 447, 281, 434])

In [47]:
r1[:]

array([[108, 380, 423, 459, 443, 179, 494, 450],
       [454, 153, 166, 326, 114, 390, 340, 380],
       [243, 328, 463, 416, 158, 237, 193, 186],
       [486, 255, 464, 488, 485, 241, 345, 311],
       [200, 104, 191, 423, 235, 149, 293, 417],
       [370, 283, 351, 436, 102, 477, 205, 163],
       [281, 383, 412, 338, 469, 403, 267, 465],
       [394, 272, 374, 292, 302, 373, 172, 113],
       [206, 130, 117, 153, 168, 447, 281, 434],
       [100, 113, 285, 462, 231, 170, 231, 312]])

In [48]:
r1[3:7,2:6]   ## rows,columns

array([[464, 488, 485, 241],
       [191, 423, 235, 149],
       [351, 436, 102, 477],
       [412, 338, 469, 403]])

In [49]:
r1[3:4,3:4]

array([[488]])

In [50]:
r1[3,3]

488

In [51]:
r1[3][3]

488

In [52]:
## Numpy Functions/Methods

In [53]:
np.random.seed(100)
r1 = np.random.randint(1,10,(5,4))
r1

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5]])

In [54]:
print(np.max(r1))
print(np.max(r1,axis=0))   ## column wise
print(np.max(r1,axis=1))    ## row wise

9
[9 9 9 8]
[9 8 6 9 7]


In [55]:
## gives the index of max number
print(np.argmax(r1))
print(np.argmax(r1,axis=0))   ## column wise
print(np.argmax(r1,axis=1))    ## row wise

0
[0 0 3 0]
[0 0 0 2 1]


In [56]:
print(np.min(r1))
print(np.min(r1,axis=0))   ## column wise
print(np.min(r1,axis=1))    ## row wise

1
[1 1 3 3]
[4 1 3 1 1]


In [57]:
## gives the index of min number
print(np.argmin(r1))
print(np.argmin(r1,axis=0))   ## column wise
print(np.argmin(r1,axis=1))    ## row wise

5
[4 1 2 1]
[2 1 1 1 0]


In [58]:
print(np.sum(r1))
print(np.sum(r1,axis=0))   ## column wise
print(np.sum(r1,axis=1))    ## row wise

95
[26 21 24 24]
[30 17 15 17 16]


In [59]:
print(np.mean(r1))
print(np.mean(r1,axis=0))   ## column wise
print(np.mean(r1,axis=1))    ## row wise

4.75
[5.2 4.2 4.8 4.8]
[7.5  4.25 3.75 4.25 4.  ]


In [60]:
r1.shape

(5, 4)

In [68]:
r1_1 = r1.reshape(20)
r1_1

array([ 9,  9,  4,  8,  8, 10,  5,  3,  6,  3,  3,  3,  2,  1,  9,  5,  1,
        7,  3,  5])

In [62]:
r1_2 = r1.reshape((2,10))  ## (4,5), (2,10),(10,2),(20,1),(1,20)
r1_2

array([[9, 9, 4, 8, 8, 1, 5, 3, 6, 3],
       [3, 3, 2, 1, 9, 5, 1, 7, 3, 5]])

In [73]:
r1_3 = r1.reshape((5,2,2))
r1_3

array([[[ 9,  9],
        [ 4,  8]],

       [[ 8, 10],
        [ 5,  3]],

       [[ 6,  3],
        [ 3,  3]],

       [[ 2,  1],
        [ 9,  5]],

       [[ 1,  7],
        [ 3,  5]]])

In [64]:
r1

array([[9, 9, 4, 8],
       [8, 1, 5, 3],
       [6, 3, 3, 3],
       [2, 1, 9, 5],
       [1, 7, 3, 5]])

In [65]:
r1[1,1] = 10

In [66]:
r1

array([[ 9,  9,  4,  8],
       [ 8, 10,  5,  3],
       [ 6,  3,  3,  3],
       [ 2,  1,  9,  5],
       [ 1,  7,  3,  5]])