In [1]:
import numpy as np

In [3]:
a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr=np.arange(0, 10, 2)
print(arr)
arr=np.arange(10)
print(arr)


[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

print("Sum of arr1:", arr1.sum())
print("Mean of arr2:", arr2.mean())

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Sum of arr1: 6
Mean of arr2: 5.0


In [21]:
arr = np.random.randint(0, 10, 5)

In [22]:
print(arr[1:4])
print(arr[:2])
print(arr[2:])
print(arr[::2])

[0 7 5]
[0 0]
[7 5 6]
[0 7 6]


In [24]:
data = np.random.randint(0, 10, 10)
print(data)
print(np.mean(data))
print(np.median(data))
print(data[np.argmax(np.bincount(data))])

[2 3 0 0 7 3 5 5 7 8]
4.0
4.0
2


In [26]:
arr=np.random.randint(100,500,10)
arr

array([280, 256, 305, 225, 444, 291, 299, 329, 120, 333])

In [30]:
reshape_arr=arr.reshape(2,5)
reshape_arr

array([[280, 256, 305, 225, 444],
       [291, 299, 329, 120, 333]])

In [32]:
trans_arr = reshape_arr.T
trans_arr

array([[280, 291],
       [256, 299],
       [305, 329],
       [225, 120],
       [444, 333]])