In [2]:
import numpy as np

In [3]:
list_arr=[1,2,3,4]
a1D = np.array(list_arr)
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a1D)

[1 2 3 4]


In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
arr=np.arange(0, 10, 2)
print(arr)
arr=np.arange(10)
print(arr)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


In [13]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

print("Sum of arr1:", arr1.sum())
print("Mean of arr2:", arr2.mean())

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Sum of arr1: 6
Mean of arr2: 5.0


In [4]:
arr = np.random.randint(0, 10, 5)
arr

array([1, 4, 3, 1, 6])

In [5]:
print(arr[1:4])
print(arr[:2])
print(arr[2:])
print(arr[::2])

[4 3 1]
[1 4]
[3 1 6]
[1 3 6]


In [6]:
data = np.random.randint(0, 10, 10)
print(data)
print(np.mean(data))
print(np.median(data))
print(data[np.argmax(np.bincount(data))])

[9 9 8 7 3 7 3 5 4 5]
6.0
6.0
7


In [7]:
arr=np.random.randint(100,500,10)
arr

array([120, 475, 147, 371, 390, 208, 168, 162, 328, 159])

In [8]:
reshape_arr=arr.reshape(2,5)
reshape_arr

array([[120, 475, 147, 371, 390],
       [208, 168, 162, 328, 159]])

In [9]:
trans_arr = reshape_arr.T
trans_arr

array([[120, 208],
       [475, 168],
       [147, 162],
       [371, 328],
       [390, 159]])